### PR TITLE
Only work around webbrowser bug if needed.

### LINKED ISSUE #94: $BROWSER var empy when using --run script
## Expected behaviour:

Open $BROWSER to the desired URL

## Actual behaviour:

Var $BROWSER is empty, you can see it by doing for example `urlscan -r 'echo $BROWSER {} > plpl' test.txt; cat plpl`

I've seen that other environment variable aren't empty (I tried a few, for example $TERMINAL and $EDITOR)

## How to reproduce:

+ Have either `export BROWSER=firefox` in your shell rc or `BROWSER=firefox` in /etc/environment

+ Have a linkhandler script which can be as simple as:

```
#!/bin/sh
$BROWSER $1
```

+ Have a test file:

```
www.google.com
pluto
https://youtube.com
```

+ Run urlscan:

`urlscan --run 'linkhandler {}' test.txt`

## Extra info:

I tried piping it too, but with no result:

`urlscan --run 'xargs linkhandler' --pipe test.txt`

## Version:

```
$ cat /proc/version
Linux version 5.5.5-arch1-1 (linux@archlinux) (gcc version 9.2.1 20200130 (Arch Linux 9.2.1+20200130-2)) #1 SMP PREEMPT Thu, 20 Feb 2020 18:23:09 +0000
```

```
$ pacman -Qi urlscan
Name            : urlscan
Version         : 0.9.4-2
Description     : Mutt and terminal url selector
Architecture    : any
URL             : https://github.com/firecat53/urlscan
Licenses        : GPL2
Groups          : None
Provides        : None
Depends On      : python-urwid
Optional Deps   : xclip: Clipboard support for X11 environments [installed]
Required By     : None
Optional For    : None
Conflicts With  : None
Replaces        : None
Installed Size  : 154.25 KiB
Packager        : Felix Yan <felixonmars@archlinux.org>
Build Date      : Mon 04 Nov 2019 08:47:38 AM CET
Install Date    : Fri 15 Nov 2019 12:08:04 PM CET
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature
```

### PR DESCRIPTION
**Pull request by ryneeverett**
This should resolve #94 as much as it can be.

My primary motivation however is to avoid overriding the predefined
browser types when possible. A lot of work has gone into making the
predefined types work well and we should have advantage of them.

### CODE REVIEW

**Comment by firecat53** [comment]
Couple of questions:

1. Do we even need this whole workaround any more? The [bug report](https://bugs.python.org/issue31014) says it's been closed/fixed since 2018.
2. Does my `browser_var_empty` work for you? It basically just removes the workaround entirely.

Thanks for working on this!

**Comment by ryneeverett** [comment]
Feel free to close and go the deletion route, I just threw this out there as a backwards compatible alternative in case there were reservations with that approach.

**Comment by ryneeverett** [comment]
The bug must have only existed in a few old patch releases so I say delete!

**Comment by firecat53** [comment]
That's my inclination as well. I'd just like to make sure the OP from #94 is able to get things working as they're supposed to. Thanks!

**Pull request closed without merging**
